package com.app.exoplanethunter.exoplanet.data.local

import android.content.Context
import androidx.datastore.core.DataStore
import androidx.datastore.preferences.core.Preferences
import androidx.datastore.preferences.core.edit
import androidx.datastore.preferences.core.stringSetPreferencesKey
import androidx.datastore.preferences.preferencesDataStore
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.map

private val Context.favoritesDataStore: DataStore<Preferences> by preferencesDataStore(name = "favorites_prefs")

/**
 * Stores the set of favorited planets, keyed by [Exoplanet.planetName] rather than the Room id.
 *
 * Names are used because a manual catalog sync deletes and re-inserts every row, which reassigns
 * the autogenerated ids — names (NASA `pl_name`) stay stable. Living in DataStore (not the
 * asset-backed catalog DB) also means a destructive catalog migration can never wipe favorites.
 */
class FavoritesPreferences(private val context: Context) {

    companion object {
        val FAVORITE_PLANET_NAMES = stringSetPreferencesKey("favorite_planet_names")
    }

    val favoriteNames: Flow<Set<String>> = context.favoritesDataStore.data
        .map { preferences ->
            preferences[FAVORITE_PLANET_NAMES] ?: emptySet()
        }

    suspend fun toggle(planetName: String) {
        context.favoritesDataStore.edit { preferences ->
            val current = preferences[FAVORITE_PLANET_NAMES] ?: emptySet()
            preferences[FAVORITE_PLANET_NAMES] =
                if (planetName in current) current - planetName else current + planetName
        }
    }
}
